name: fungible-assets-indexer
field_selection:
  transaction_fields:
    - "hash"
contracts:
  - name: USDT_Ethereum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: USDC_Ethereum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: USDS_Ethereum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: USDe_Ethereum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: DAI_Ethereum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: PYUSD_Ethereum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: USD1_Ethereum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: sUSDS_Ethereum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: sUSDe_Ethereum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: WETH_Ethereum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: wstETH_Ethereum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: weETH_Ethereum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: liquidUSD_Ethereum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: liquidETH_Ethereum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: ETHFI_Ethereum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: WBTC_Ethereum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: cbBTC_Ethereum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: PAXG_Ethereum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: XAUt_Ethereum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: PEPE_Ethereum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: USDT_Base
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: USDC_Base
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: USDS_Base
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: USDe_Base
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: DAI_Base
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: sUSDS_Base
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: sUSDe_Base
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: WETH_Base
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: wstETH_Base
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: weETH_Base
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: ETHFI_Base
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: cbBTC_Base
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: USDT_Arbitrum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: USDC_Arbitrum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: USDS_Arbitrum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: USDe_Arbitrum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: DAI_Arbitrum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: PYUSD_Arbitrum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: sUSDS_Arbitrum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: sUSDe_Arbitrum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: WETH_Arbitrum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: wstETH_Arbitrum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: weETH_Arbitrum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: ETHFI_Arbitrum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: WBTC_Arbitrum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: cbBTC_Arbitrum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: PEPE_Arbitrum
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: USDT_Scroll
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: USDC_Scroll
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: USDe_Scroll
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: DAI_Scroll
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: WETH_Scroll
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: wstETH_Scroll
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: weETH_Scroll
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: liquidUSD_Scroll
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: liquidETH_Scroll
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
  - name: WBTC_Scroll
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
networks:
  - id: 1
    start_block: 24670719
    contracts:
      - name: USDT_Ethereum
        address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
      - name: USDC_Ethereum
        address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
      - name: USDS_Ethereum
        address: "0xdC035D45d973E3EC169d2276DDab16f1e407384F"
      - name: USDe_Ethereum
        address: "0x4c9EDD5852cd905f086C759E8383e09bff1E68B3"
      - name: DAI_Ethereum
        address: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
      - name: PYUSD_Ethereum
        address: "0x6c3ea9036406852006290770BEdFcAbA0e23A0e8"
      - name: USD1_Ethereum
        address: "0x8d0D000Ee44948FC98C9B98A4FA4921476f08b0D"
      - name: sUSDS_Ethereum
        address: "0xa3931d71877C0E7a3148CB7Eb4463524FEc27fbD"
      - name: sUSDe_Ethereum
        address: "0x9D39A5DE30e57443BfF2A8307A4256c8797A3497"
      - name: WETH_Ethereum
        address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
      - name: wstETH_Ethereum
        address: "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0"
      - name: weETH_Ethereum
        address: "0xCd5fE23C85820F7B72D0926FC9b05b43E359b7ee"
      - name: liquidUSD_Ethereum
        address: "0x08c6F91e2B681FaF5e17227F2a44C307b3C1364C"
      - name: liquidETH_Ethereum
        address: "0xf0bb20865277aBd641a307eCe5Ee04E79073416C"
      - name: ETHFI_Ethereum
        address: "0xFe0c30065B384F05761f15d0CC899D4F9F9Cc0eB"
      - name: WBTC_Ethereum
        address: "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
      - name: cbBTC_Ethereum
        address: "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf"
      - name: PAXG_Ethereum
        address: "0x45804880De22913dAFE09f4980848ECE6EcbAf78"
      - name: XAUt_Ethereum
        address: "0x68749665FF8D2d112Fa859AA293F07a622782F38"
      - name: PEPE_Ethereum
        address: "0x6982508145454Ce325dDbE47a25d4ec3d2311933"
  - id: 8453
    start_block: 43442249
    contracts:
      - name: USDT_Base
        address: "0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2"
      - name: USDC_Base
        address: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
      - name: USDS_Base
        address: "0x820C137fa70C8691f0e44dc420a5e53c168921Dc"
      - name: USDe_Base
        address: "0x5d3a1Ff2b6BAb83b63cd9AD0787074081a52ef34"
      - name: DAI_Base
        address: "0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb"
      - name: sUSDS_Base
        address: "0x5875eee11cf8398102fdad704c9e96607675467a"
      - name: sUSDe_Base
        address: "0x211Cc4DD073734dA055fbF44a2b4667d5E5fE5d2"
      - name: WETH_Base
        address: "0x4200000000000000000000000000000000000006"
      - name: wstETH_Base
        address: "0xc1CBa3fCea344f92D9239c08C0568f6F2F0ee452"
      - name: weETH_Base
        address: "0x04C0599Ae5A44757c0af6F9eC3b93da8976c150A"
      - name: ETHFI_Base
        address: "0x6C240DDA6b5c336DF09A4D011139beAAa1eA2Aa2"
      - name: cbBTC_Base
        address: "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf"
  - id: 42161
    start_block: 442423696
    contracts:
      - name: USDT_Arbitrum
        address: "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"
      - name: USDC_Arbitrum
        address: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
      - name: USDS_Arbitrum
        address: "0x6491c05A82219b8D1479057361fF1654749b876b"
      - name: USDe_Arbitrum
        address: "0x5d3a1Ff2b6BAb83b63cd9AD0787074081a52ef34"
      - name: DAI_Arbitrum
        address: "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"
      - name: PYUSD_Arbitrum
        address: "0x46850ad61c2b7d64d08c9c754f45254596696984"
      - name: sUSDS_Arbitrum
        address: "0xddb46999f8891663a8f2828d25298f70416d7610"
      - name: sUSDe_Arbitrum
        address: "0x211Cc4DD073734dA055fbF44a2b4667d5E5fE5d2"
      - name: WETH_Arbitrum
        address: "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"
      - name: wstETH_Arbitrum
        address: "0x5979D7b546E38E414F7E9822514be443A4800529"
      - name: weETH_Arbitrum
        address: "0x35751007a407ca6FEFfE80b3cB397736D2cf4dbe"
      - name: ETHFI_Arbitrum
        address: "0x7189fb5B6504bbfF6a852B13B7B82a3c118fDc27"
      - name: WBTC_Arbitrum
        address: "0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f"
      - name: cbBTC_Arbitrum
        address: "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf"
      - name: PEPE_Arbitrum
        address: "0x25d887Ce7a35172C62FeBFD67a1856F20FaEbB00"
  - id: 534352
    start_block: 32009788
    contracts:
      - name: USDT_Scroll
        address: "0xf55BEC9cafDbE8730f096Aa55dad6D22d44099Df"
      - name: USDC_Scroll
        address: "0x06eFdBFf2a14a7c8E15944D1F4A48F9F95F663A4"
      - name: USDe_Scroll
        address: "0x5d3a1Ff2b6BAb83b63cd9AD0787074081a52ef34"
      - name: DAI_Scroll
        address: "0xcA77eB3fEFe3725Dc33bccB54eDEFc3D9f764f97"
      - name: WETH_Scroll
        address: "0x5300000000000000000000000000000000000004"
      - name: wstETH_Scroll
        address: "0xf610A9dfB7C89644979b4A0f27063E9e7d7CDA32"
      - name: weETH_Scroll
        address: "0x01f0a31698C4d065659b9bdC21B3610292a1c506"
      - name: liquidUSD_Scroll
        address: "0x08c6F91e2B681FaF5e17227F2a44C307b3C1364C"
      - name: liquidETH_Scroll
        address: "0xf0bb20865277aBd641a307eCe5Ee04E79073416C"
      - name: WBTC_Scroll
        address: "0x3C1BCa5a656e69edCD0D4E36BEbb3FcDAcA60Cf1"
